### ISSUE TITLE
Add implementation to circle of writers

### ISSUE THREAD

**Issue by nikolasFreitas** [orion-services/activity#50]
### Tasks to complete this task:

- [x] Add step circle of writers.
- [x] Add verify method
- [x] Add finished method
- [x] Add param of multiple rounds
- [x] Add use creator to document entity.

**Comment by nikolasFreitas** [comment]
@ManyToOne
    @JoinColumn(name = "group_id")
    private GroupActivity groupActivity;
